<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StarExplorer.Shared\StarExplorer.Shared.csproj" />
    <ProjectReference Include="..\StarExplorer.WindowsBackend\StarExplorer.WindowsBackend.csproj" />
  </ItemGroup>

</Project>
